### ISSUE TITLE
html page does not expand to window extents

### ISSUE THREAD

**Issue by davehorner** [mattsse/chromiumoxide#101] opened 2022-09-26 13:26 UTC
Below is the code I am using to test oxide.
```
    let baseurl = "http://www.google.com".to_owned();
    let (browser, mut handler) =
      Browser::launch(BrowserConfig::builder().with_head().build()?).await?;
    let handle = tokio::task::spawn(async move {
        loop {
            let _ = handler.next().await.unwrap();
        }
    });

    let _p = browser.new_page(baseurl.clone()).await?;
    handle.await?;
    Ok(())
```

The page comes up and the viewport/webpage is not expanding to the window extents.  Is there something that would cause this resize issue?

**Comment by davehorner** [comment] 2022-10-19 11:51
I've tried setting a height and width and creating a viewport too.  Sometimes the viewport will size correctly.

```
   Browser::launch(BrowserConfig::builder()
      .viewport(Viewport { width: 1190, height: 800, device_scale_factor: None, emulating_mobile: false, is_landscape: true, has_touch: false })
      .window_size(1190,800)
```

I don't think setting the window_size and viewport are the fix.  I couldn't come up with any other ideas on triangulating what the ultimate cause.  Chrome does not exhibit the same behavior when run normally.

It's sizing this morning on my machine properly.  I was going to close the ticket but I still experience it intermittently.
If someone else is experiencing the sizing issues too, that helps.

**Comment by d4h0** [comment] 2023-03-16 13:35
This seems to be a duplicate of https://github.com/mattsse/chromiumoxide/issues/100

**Comment by davehorner** [comment] 2023-03-16 13:54
This is not nodejs or puppeteer,  I don't understand the resolution.  I stopped using chromiumoxide because I couldn't get this figured out.

**Closed** 2024-05-03 12:29 UTC
