### ISSUE TITLE
Error `unknown flag 'disable-background-networking'` while using with Chromium

### ISSUE THREAD

**Issue by RiddleMan** [mattsse/chromiumoxide#186] opened 2023-11-03 19:39 UTC
I experience an error while using chromiumoxide with Chromium 119.0.6045.105 on Ubuntu 22.04. I run the latest version of chromiumoxide from `main` branch at the moment of writing it's _88470cabec15ffc2a91dc5579ec142e921d59eab_.

I get this error:
![image](https://github.com/mattsse/chromiumoxide/assets/1132905/4a7b70ed-b1fa-4862-8147-cd687e086d0a)

**Comment by jloupdef** [comment] 2023-12-29 19:27
Hi, I encountered the same issue and narrow it down to the canonicalize function of either async_std or tokio, the issue is chromium is installed through snap and the chromium is a symbolic link to /usr/bin/snap. canonicalize follow the symlink to use the real executable which does not work in this case as snap should not be called directly.
chromium identified first as /snap/bin/chromium

Then canonicalize transforms it to /usr/bin/snap

Only way/Easiest way to handle this is to cancel the canonicalize if the final path is targetting snap, needs to be done/fixed in this plugin, there is no workaround I can think of.

I might give it a shot next year as I won't have access to a computer for the next few days.
Have a good New Year's Eve !

**Closed** 2024-09-06 12:17 UTC
